### ISSUE TITLE
feature request: configurable zoom levels

### ISSUE THREAD

**Issue by wilco1967** [yaapu/HorusMappingWidget#18]
Perhaps, may I suggest a small improvement, which would make it even more useful for long range flying ?
Now, I can select the starting zoom level in the configuration (for example 0). The zoom level channel then lets me change between -2, -1 and 0.
I could also set the starting zoom to say 3. It would then let me change between 1, 2 and 3.
'trouble' is, those 3 zoom levels are not so much different from each other.

It would be even nicer, if I can define the three different zoom levels individually in the configurator. For example, -2, 0, +3
This gives me a nice detail when close by, and a nice large overview when far away....

I often fly long range, and on too high detail, I loose the overview where the plane is....

Even better would be allowing more than 3 different zoom levels (say 6), by using for example the S2 potmeter (or perhaps the 6 position switches).

**Comment by Papsi77** [comment]
+1 
Would be great if the function was implemented.

**Comment by ReinhardZ1** [comment]
Isn't it possible to just rename the tile folders from e.g. -2, 0, 3 to -1, 0, 1 ?

**Comment by handbrems** [comment]
@ReinhardZ1 
Have you tried that? Is it possible just by renaming the folders?

**Comment by ReinhardZ1** [comment]
I have tried it meanwhile and unfortunately the map is not shown after renaming the folders.

**Comment by handbrems** [comment]
The names of the folders are probably geo-coded you cannot rename them without destroying the map structure. 
Too bad.

**Comment by yaapu** [comment]
Please test this new version and report back.

[HorusMappingWidget_1.2.1dev.zip](https://github.com/yaapu/HorusMappingWidget/files/6331109/HorusMappingWidget_1.2.1dev.zip)

check the /CFG/examples/yaapudev_sensors_maps.lua it has the zoomLevels table to define valid zoom levels.
This version also supports google maps as mapping provider, to download the maps you need to follow the "other" wiki here

Thanks a lot for raising the issue and for the "long" patience :-)

**Comment by Papsi77** [comment]
I tested version 1.2.1 today.
The zoom level and switching work without any problems.

However, I found a bug:
When you start the script you only get a blue screen, the GPS coordinates and the telemetry values can be seen below and on the right side.
You then have to change the zoom level once and then the maps are displayed.

**Comment by yaapu** [comment]
ok thanks, found the bug
try this one 
[HorusMappingWidget-1.2.2dev.zip](https://github.com/yaapu/HorusMappingWidget/files/6331794/HorusMappingWidget-1.2.2dev.zip)

**Comment by Papsi77** [comment]
Perfect - problem solved.

Thank you for this and your other scripts
