### ISSUE TITLE
How to make this sensors work with BF... on the same TX iNav works !

### ISSUE THREAD

**Issue by yo8aiv** [yaapu/HorusMappingWidget#19]
Hi and thanks for the great script.

How can i make BF sensors (map works fine and shows position) work with this script ... on the same TX iNav works ! basically i just changed quad and created new model on my T16S.
should i copy and rename and change the config ?
thing is with BF i don;t see any config being generated. 

Thx.

**Comment by yaapu** [comment]
hi, should work just fine, check you discovered all sensors and that the names match what you defined in the config file

**Comment by yo8aiv** [comment]
yes .. it worked. just needed to manually create 3 more files. THX.
