### ISSUE TITLE
feature request: GMapCatcher selectable zoom levels

### ISSUE THREAD

**Issue by MrD-RC** [yaapu/HorusMappingWidget#22]
Apologies, this is a feature request for the GMapCatcher tool. There is no issues tab on that repo, so I've added it here.

What I'd like to see is a change or addition to the download dialogue box. Currently in the zoom area, there are minimum and maximum boxes. However, I think those zoom levels are too close together, and I would rather have more spaced out zoom levels. I would be great if there was just a loom levels box, where you could have a comma separated list of the zoom levels you would like to download. For example: -1, 1, 4

This would also sync up nicely with the https://github.com/yaapu/HorusMappingWidget/issues/18 feature request

**Comment by yaapu** [comment]
Hi, please post your issue here
https://github.com/heldersepu/GMapCatcher
