### ISSUE TITLE
No sensors 

### ISSUE THREAD

**Issue by Eg681** [yaapu/HorusMappingWidget#24]
I'm trying to open yaapu sensors page following directions on github, I've created model_sensors_maps.lua in yaapu cfg page but when opened after running maps on radiomaster tx16s no sensors, were are the sensors? I've tried this several times and have watched many videos but still no joy. Inav telemetry working fine same radio same wing. Were is the yaapu sensors?

**Comment by yaapu** [comment]
Your's doesn't sound like an issue but rather a configuration error, please post on [rc groups](https://www.rcgroups.com/forums/showthread.php?3557943-Yaapu-Horus-Mapping-Widget-for-iNAV-Betaflight) asking for help
