### ISSUE TITLE
EthOS Support for FRSKY X20

### ISSUE THREAD

**Issue by LordGeorge-1992** [yaapu/HorusMappingWidget#28]
What is the chances of this great widget seeing a branch for the new EthOS?
Very Tempted to see this in action on the new X20 ;)

Amazing work as usual dude!
Thanks

**Comment by MrD-RC** [comment]
EthOS needs to support LUA scripts first.

**Comment by yaapu** [comment]
I do have an X20 for development and I've been assured by the Ethos author that there will be LUA support, so fingers crossed :-)
