### ISSUE TITLE
iNav: add support for displaying home and calculate home distance and bearing

### ISSUE THREAD

**Issue by yaapu** [yaapu/HorusMappingWidget#3]

**Comment by lossUAVes** [comment]
Hi, I love this widget. Thank you.
I'm trying to run it in iNav, but I only have No telemetry data message.

INAV 2.5.1. FPort serial protocol.
Holybro Kakute F7 mini flight controller.
Frsky R-XSR receiver. Firm: RXSR_ACCST_2.1.0_Fport_LBT
RadioMaster TX16S transmitter. Firm: multi-stm-opentx-aetr-noinv-v1.3.1.36
OpenTX 2.3.9. Firm: opentx-tx16s-lua-noheli-es-2.3.9-otx
SD Card contents: sdcard-480x272-2.3V0029
Yaapu telemetry widget 1.8.1.

INAV telemetry lua script is working fine.

**Comment by yaapu** [comment]
Which widget are you trying to run? The Yaapu Telemetry Widget or the HorusMappingWidget?
The former does not work with iNAV and only support ArduPilot!

**Comment by lossUAVes** [comment]
Ah, sorry... I didn't know that there was two widgets... HorusMappingWidget is working. Thanks.

**Comment by yaapu** [comment]
no worries :-)

**Comment by yaapu** [comment]
added in version 2.0.0
