### ISSUE TITLE
APM Planner 2 on Linux

### ISSUE THREAD

**Issue by dentex** [yaapu/HorusMappingWidget#32]
Hi,
I installed the Mission Planner in order to download the maps tiles, but I had a few issues. 
This new v2 downloads the files into `/home/$USER/apmplanner2/mapscache/Data.qmdb`.
I run the resize tool in wine and I was not able to let it point to this dir because it exposes some hard-coded paths mixing windows and Linux path separators (images for reference). How to proceed? Thanks.

![apm](https://user-images.githubusercontent.com/2931982/115759506-9c75e900-a3a0-11eb-8ed1-07fbc370b56f.png)
![tool](https://user-images.githubusercontent.com/2931982/115759526-a0a20680-a3a0-11eb-9a7d-c28606c8739d.png)

**Comment by yaapu** [comment]
Hi, that's APM Planner, I only support mission planner, different product.
As for running the resize tool on linux, that's another story, need to experiment with it, for now I'd suggest copying the downloaded tiles to a wine reachable path

**Comment by dentex** [comment]
Oh OK, I see now they are two different products. Unfortunately Mission Planner is a windows only application and under wine gives too many errors and it doesn't even install. So I'm out. 
Sorry.
