### ISSUE TITLE
gmapcatcher is not downloading any tiles

### ISSUE THREAD

**Issue by jasc76** [yaapu/HorusMappingWidget#35]
hi

the included gmapcatcher 0.8.1 is not displaying or downloading any tiles. I tried with the most current version from the gmapcatcher website and it seems to work fine. Of course your version is patched to export the correct files. Could you please look into that ??

Regards
jan

**Comment by yaapu** [comment]
did you try the updated version here?
https://github.com/yaapu/GMapCatcher/releases/tag/yaapu-0.8.2.1
