### ISSUE TITLE
 no map data yaapu radiomaster tx16s tried everything :(

### ISSUE THREAD

**Issue by allibongo** [yaapu/HorusMappingWidget#39]
Ihave exactly the same problem on radiomaster tx16s&tried everything :(

__Originally posted by @allibongo in https://github.com/yaapu/HorusMappingWidget/issues/37#issuecomment-906457040__

**Comment by fabi9163** [comment]
Also had this problem. Have you tried to set a scroll-channel? The default-scroll-level had no map-data. As I scrolled to another level the map showed up.

**Comment by yaapu** [comment]
stale issue
