### ISSUE TITLE
1.2.2b Telemetry Data is shown but no map

### ISSUE THREAD

**Issue by bokie1** [yaapu/HorusMappingWidget#43]
Getting bald pulling my hair.
I have telemetry data on the right and bottom. I even have the GPS coordinates. The only thing missing is the map. I'm on 1.2.2b.

**Comment by peter9x** [comment]
The name of your image files starts with s_ ?

**Comment by yaapu** [comment]
closing as it's a bit old, if not solved please reopen, thanks
