### ISSUE TITLE
No GPS being detected.

### ISSUE THREAD

**Issue by lenztech** [yaapu/HorusMappingWidget#44]
I recently installed the mapping widget and it does not detect my GPS. I have the LuaTelemetry widget installed and it is detecting the GPS with no issues. I have a Horus X10 express radio running OpenTX. The aircraft is a wing with Matek f405se with INAV and a Frsky X8R receiver. Any help will be appreciated

**Comment by yaapu** [comment]
The widget looks for a sensor named "GPS", what's your sensor name?
I'm closing since is a bit old, please reopen if not solved yet
