### ISSUE TITLE
Request: ETHOS port

### ISSUE THREAD

**Issue by MrD-RC** [yaapu/HorusMappingWidget#47]
Hi Alessandro. Are there any plans to port this awesome script to ETHOS? I see your FrSky telemetry script has an ETHOS version. I'd love to see the mapping widget on ETHOS too, as quite simply it blows all the current mapping widgets out the sky. The don't come close to this widget.

Thanks for all your work 👍

**Comment by yaapu** [comment]
Hi, please test and report :-)

https://github.com/yaapu/EthosMappingWidget
