### ISSUE TITLE
Unable to set « GoogleTerrainMap » as map type

### ISSUE THREAD

**Issue by dxs94** [yaapu/HorusMappingWidget#50]
I have both satellite and terrain maps installed, but in the configurator widget (TX16S, OTX2.3.15, latest GitHub for the mapping widget), when I select « Google » then « googleterrainmap « , the choice always reverts to « googlesatellitemap « , hence my terrain maps are never loaded. By revert I mean I can select it but it is never saved upon leaving the configurator.
All other possible choices of map provider and map type do stick, just this one (Google terrain maps) does not.

**Comment by yaapu** [comment]
fixed, please download latest zip
