### ISSUE TITLE
OpenTX  2.3.15  Taranis 2019 SE problem

### ISSUE THREAD

**Issue by EjectSteve** [yaapu/HorusMappingWidget#55]
I have 2 ardupilot planes and 2 models on my Taranis (model X and model Y).   The first model works with Yaapu no problem model X, taranis model X. The second model just shows 'no telemetry' Model Y, Taranis Model Y.  Regular ardupilot/opentx telemetry works on both.

I thought perhaps model Y was not configured correctly in ardupilot so I tried working the Model X with Taranis Model Y and it also shows the 'no telemetry' screen but I can still see openTX telemetry. 

The ability to open the Yaapu menu from the telemetry screen has been hit or miss on a Taranis.  It worked a few times with Taranis Model X but is not working now and I also can't open the Yaapu menu for Model Y to choose opentx telemetry source.

ELRS 100hz 4:1. I have also tried 333hz 4:1 and 2:1

**Comment by EjectSteve** [comment]
It working now.  My model name had two spaces between 2 words.  I took out the spaces and the menu button worked and I could choose use crossfire.

**Comment by yaapu** [comment]
great!
