### ISSUE TITLE
Yaapu mapping on Zorro elrs

### ISSUE THREAD

**Issue by edgeflyer30** [yaapu/HorusMappingWidget#58]
Which setup do I need to get offline maps with Zorro on Edgetx and ELRS Rx with GPS sensor? So no flight controller. Thanks

**Comment by edgeflyer30** [comment]
Also I need to clarify which files to install on Zorro tx to get a Yaapu telemetry widget without a flight controller. So I am using a Matek elrs pwm wing type Elrs Rx with a GPS module on the sport pins. This Rx is a crsf elrs Rx with an attached pwm converter. I can get GPS sensor data on my tx. But I would like to see this in a Yaapu telemetry or mapping widget.

**Comment by yaapu** [comment]
you need a color LCD radio for the mapping feature and you need a flight controller running Ardupilot for the telemetry script, your setup is not supported
