### ISSUE TITLE
[suggestion] dummy GPS fix for testing

### ISSUE THREAD

**Issue by dentex** [yaapu/HorusMappingWidget#6]
Hello,
I don't know if this is somehow already implemented, but for the moment, if you want to see how the tiles and the sensors panels look like, you have to have a valid GPS fix; a real one, with the drone outside, plugged LiPO and all.
I was thinking about something like a simple text file, with fictional GPS coordinates in it; when the script finds it, it may show that fix instead of waiting for the real one. Or maybe just add an option where the user can type in the coordinates for a _testing purpose_ GPS fix, plus an enable/disable "testing" switch.

Thanks.

**Comment by yaapu** [comment]
Hi, you can do that in companion, install the widget on the simulator, enable sensors simulation and enter the gps coordinates there.

**Comment by dentex** [comment]
Great! Thanks. 
I didn't know.

**Comment by dentex** [comment]
Hey Yaapu, 
I was trying to run the script from the radio simulator. 
It seems all is set up (I have sounds, etc), but the telemetry page with the map widget won't show up.
If I run it manually from the SYS menu, I have this error (but I don't know if it's related, because the script from TOOLS runs fine):
![immagine](https://user-images.githubusercontent.com/2931982/78540381-5d581280-77f4-11ea-8efe-9f1d884c5761.png)
![immagine](https://user-images.githubusercontent.com/2931982/78542272-39e29700-77f7-11ea-94bf-5beb53e0b2a3.png)

I forgot to say that I setup a proper GPS fix in the UI, so it shows up in the sim radio; it's not grayed out:
![immagine](https://user-images.githubusercontent.com/2931982/78542191-1d465f00-77f7-11ea-8aa0-4e95d42adb5e.png)

**Comment by yaapu** [comment]
Hi, download latest version again, you hav the wrong mapsconfig.lua.

Never seen that error before, is it on linux?
Try to use [these files](https://github.com/yaapu/HorusMappingWidget/tree/master/HORUS/SOURCES/SRC) and let companion compile it for you

**Comment by dentex** [comment]
Yes Linux.

Thanks, that worked:

![immagine](https://user-images.githubusercontent.com/2931982/78547943-2be54400-7800-11ea-9ad2-22da2d43510a.png)

No sensors here, but I'll try to figure it out. 
:)

**Comment by dentex** [comment]
![immagine](https://user-images.githubusercontent.com/2931982/78553550-bd0ce880-7809-11ea-93c1-00855ec40b6a.png)

Got it!

Thanks again.

(...you have to close/re-open the sim every time you edit the script)
