### ISSUE TITLE
Mavlink support for expresslrs Mavlink

### ISSUE THREAD

**Issue by iamwinq** [yaapu/HorusMappingWidget#60]
Hi Alex!

I have just updated the expresslrs to 3.5.1 and tried using the Mavlink RC, so basically it now uses Mavlink instead of CRSF protocol. I have followed the guide as listed here:
[https://www.expresslrs.org/software/mavlink/](url)

On my radio telemetry, I can fetch the telemetry data on the sensors page. However, it seems that the yaapu script does not recognize it.. any thoughts on this? I confirm that the yaapu script is working when using CRSF protocol, but only when using the Mavlink it does not work..

**Comment by yaapu** [comment]
Hi, this is not supported, you need native CRSF telemetry from Ardupilot, what you see on your radio is fake CRSF telemetry forged from the mavlink stream
